### ISSUE TITLE
func: createUserAccount

### ISSUE THREAD

**Issue by OkoliEvans** [OkoliEvans/BLOC-AN2#1]
Function to create new account for platform user.

Params: shipping address

Expected behaviour: Maps user address to User struct.
User struct should have shipping address, total buys by user

**Comment by GideonBature** [comment]
Greetings, I want to work on this.

I have an understanding of Solidity and also familiar with structs etc.

**Comment by OkoliEvans** [comment]
> Greetings, I want to work on this.
> 
> I have an understanding of Solidity and also familiar with structs etc.

Issue has been assigned to @GideonBature , pls open a PR in 3 days no matter what you were able to accomplish by then. We can then review and you can continue working on it

**Comment by GideonBature** [comment]
alright, Thank  you! 

I was able to create the function and requested for a pull request, anytime you are chanced, you can check it to see if it's okayyy, or I need to make some changes to what I have done...
