### ISSUE TITLE
func addProduct

### ISSUE THREAD

**Issue by OkoliEvans** [OkoliEvans/BLOC-AN2#11]
Desc: Adds a new product to the store. Only registered vendors are granted access. Map productId to Product struct for easy manipulations

Product struct should have properties: product id,  product owner (address), product description, product category, product amount, product manufacturing date, product expiry date, product condition.

Params: product description, product category, product amount, product manufacturing date, product expiry date, product condition, product image (ipfs CID)

PS: There should be an enum containing product categories: clothings, electronics, appliances, furniture, plastics, phones, foot wears, laptops, others
PSS: There should be a second enum containing product condition: brand new, foreign used, Nigerian used

**Comment by getgiddy** [comment]
I would love to work on this boss. @OkoliEvans

**Comment by OkoliEvans** [comment]
Awesome, assigned @getgiddy 
Thank you.

Try to open a PR within 3 days irrespective of how far you have gone, and don't hesitate to reach out if you encounter any blockers you can't resolve.

**Comment by getgiddy** [comment]
@OkoliEvans I created a PR for this issue - https://github.com/OkoliEvans/BLOC-AN2/pull/15

**Comment by getgiddy** [comment]
I had changed some variable names and added a few others I thought were necessary. I would love your feedback on whether those were acceptable decisions.
