### ISSUE TITLE
func updateProduct

### ISSUE THREAD

**Issue by OkoliEvans** [OkoliEvans/BLOC-AN2#12]
Desc: Updates already uploaded product on the store using the productId to access the product. Only vendor that uploaded the product is granted access.

Product struct should be updated with the new data.

Params: product description, product category, product amount, product manufacturing date, product expiry date, product condition, product image (ipfs CID)

see issue #11 for details on how the product details is created, also this issue should be handled only after issue no. 11

**Comment by getgiddy** [comment]
@OkoliEvans  Seeing as this is a sequel to #11, I would love to work on this.

**Comment by OkoliEvans** [comment]
Super, assigned @getgiddy

**Comment by getgiddy** [comment]
@OkoliEvans PR opened - https://github.com/OkoliEvans/BLOC-AN2/pull/16

I'm so sorry, I couldn't work on this fast enough because I was away for a while.
