### ISSUE TITLE
Func: createVendorAccount

### ISSUE THREAD

**Issue by OkoliEvans** [OkoliEvans/BLOC-AN2#2]
Function for vendors to create account

Params: home address, wallet address to receive payment, phone number

Desc: Map vendor address (msg.sender) to Vendor struct. Struct should have home address, phone number and wallet address to receive payment

**Comment by getgiddy** [comment]
Hello @OkoliEvans,

I would love to work on this

**Comment by OkoliEvans** [comment]
> Hello @OkoliEvans,
> 
> I would love to work on this

Issue has been assigned to @getgiddy  , pls open a PR in 3 days no matter what you were able to accomplish by then. We can then review and you can continue working on it

**Comment by getgiddy** [comment]
@OkoliEvans I opened a PR for this feature. I apologize for overshooting the timeframe given.

https://github.com/OkoliEvans/BLOC-AN2/pull/10
